var NAVTREEINDEX6 =
{
"styleguide.html#conditional-compilation":[0,1,10],
"styleguide.html#constants-macros":[0,1,4],
"styleguide.html#directory_structure":[0,0],
"styleguide.html#exit-functions":[0,1,7],
"styleguide.html#fork":[0,2,1,0],
"styleguide.html#function-return-values":[0,1,8],
"styleguide.html#functions":[0,1,6],
"styleguide.html#git":[0,2],
"styleguide.html#git-mechanics":[0,2,2],
"styleguide.html#includes":[0,1,3],
"styleguide.html#indentation":[0,1,0],
"styleguide.html#inline":[0,1,9],
"styleguide.html#naming":[0,1,2],
"styleguide.html#outside-master":[0,2,1],
"styleguide.html#pr":[0,2,1,1],
"styleguide.html#source_style":[0,1],
"styleguide.html#typedefs":[0,1,5]
};
